# user's config file for testing proc

## pre-testing power analysis
pre_mu_diff: 1
pre_sd: 2
pre_pow_lev: 0.8
pre_alpha: 0.05
pre_alternative: two-sided

## data analysis:
eval_unit_size: 5
eval_unit_met: mean
shuffled: False
random_seed: 13
normal_test_alpha: 0.05


## sig testing
sig_test_alpha: 0.05
sig_boot_perm_B: 500
mu: 0 # null hypothesis
h1: two-sided # alternative hypothesis

## effect size
eff_size_ind: wilcoxonr
eff_size_alpha: 0.05

## power analysis
power_alpha: 0.05
power_method: bootstrap
power_dist_name: normal
power_num_of_subsample: 10 # number of simulations 
power_B: 50



## output
fig_output_dir: figures
report_output_dir: report